- apiVersion: v1
  kind: Namespace
  metadata:
    name: supriadi
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web-service
    namespace: supriadi
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: web-service
    template:
      metadata:
        labels:
          app: web-service
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: web-service
            image: localhost:8888/supriadi/web-service:latest
            ports:
              - containerPort: 3000
            resources:
              requests:
                cpu: '0'
                memory: '0'
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: web-service-svc
    namespace: supriadi
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 3000
        name: port80
        port: 8001
        protocol: TCP
    selector:
      app: web-service
