name: Docker Image Classification Engine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image
      run: docker build -t localhost:8888/supriadi/classification-engine:latest -f classification-engine/docker/api.Dockerfile ./classification-engine
    - name: push image to registry
      run: docker image push localhost:8888/supriadi/classification-engine:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: deploy latest image
      run: docker service update --image localhost:8888/supriadi/classification-engine:latest classification_engine_supriadi_classification_engine
      
      
      
