name: Docker Image Twitter Worker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Image Web Service
      run: docker build -t localhost:8888/supriadi/twitter-worker:latest -f web-service/docker/worker.Dockerfile ./web-service
    - name: push image to registry Web Service
      run: docker image push localhost:8888/supriadi/twitter-worker:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: deploy latest image
      run: docker service update --image localhost:8888/supriadi/twitter-worker:latest twitter_worker_supriadi_twitter_worker
      
      
      
