name: Docker Image Web Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: copy config
      run: cp /home/ubuntu/vault/server/.env ./web-service
    - name: Build the Docker Image
      run: docker build -t localhost:8888/supriadi/web-service:latest -f web-service/docker/api.Dockerfile ./web-service
    - name: push image to registry
      run: docker image push localhost:8888/supriadi/web-service:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: update deployment
      run: kubectl rollout restart deployment/web-api
      
      
      
